ChaiLove API: love::graphics Class Reference
love::graphics Class Reference
The primary purpose of the graphics module is to draw to the screen.
Public Member Functions
graphics & rectangle (const std::string &drawmode, int x, int y, int width, int height)
Draws a rectangle.
graphics & clear ()
Clears the screen to the set background color.
graphics & clear (int r, int g, int b, int a)
Clears the screen to the given background color.
graphics & point (int x, int y)
Draws a point.
graphics & point (Point *p)
Draws a point.
graphics & line (int x1, int y1, int x2, int y2)
Draws a line.
Quad newQuad (int x, int y, int width, int height, int sw, int sh)
Creates a new Quad.
Image * newImage (const std::string &filename)
Creates a new Image from a given filepath.
Font * newFont (const std::string &filename, int size)
Creates a new TrueType font, with the given font size.
Font * newFont (int size)
Creates a new pixel font at the given size.
Font * newFont (const std::string &filename, int glyphWidth, int glyphHeight, const std::string &letters)
Creates a new BMFont with the given spec.
graphics & setFont (Font *font)
Set an already-loaded Font as the current font.
Font * getFont ()
Retrieve th currently active font.
graphics & print (const std::string &text, int x, int y)
Prints the given text to the screen.
graphics & setColor (int red, int green, int blue, int alpha)
Sets the active drawing color to the given color.
Color getColor ()
Gets the current color.
Color getBackgroundColor ()
Retrieves the active background color.
graphics & setBackgroundColor (int red, int green, int blue, int alpha)
Sets the background color to the given color.
graphics & setDefaultFilter (const std::string &filter)
Sets the default scaling filters used with images, and fonts.
std::string getDefaultFilter ()
Returns the default scaling filters used with images and fonts.
int getWidth ()
Retrieve the width of the screen.
int getHeight ()
Retrieve the height of the screen.
Point getDimensions ()
Gets the width and height of the window.
graphics & circle (const std::string &drawmode, int x, int y, int radius)
Draws a circle.
graphics & ellipse (const std::string &drawmode, int x, int y, int radiusx, int radiusy)
Draws an ellipse.
graphics & draw (Image *image, int x, int y, float r, float sx, float sy, float ox, float oy)
Draws an image with the given angle, zoom, and origin.
graphics & draw (Image *image, Quad quad, int x, int y)
Draws an image on screen, using the given Quad as a source.
graphics & arc (const std::string &drawmode, int x, int y, int radius, int angle1, int angle2)
Draws an arc.
Detailed Description
The primary purpose of the graphics module is to draw to the screen.
Member Function Documentation
arc()
graphics& love::graphics::arc (const std::string & drawmode, int x, int y, int radius, int angle1, int angle2)
Draws an arc.
Parameters
drawmode How to draw the arc. Can be "fill" or "line".
x The position to draw the object (x-axis).
y The position to draw the object (y-axis).
radius The radius of the arc.
angle1 The angle of the first
angle2 The angle of the second.
circle()
graphics& love::graphics::circle (const std::string & drawmode, int x, int y, int radius)
Draws a circle.
Parameters
drawmode How to draw the circle. Can be "fill" or "line".
x The position of the center along x-axis.
y The position of the center along y-axis.
radius The radius of the circle.
clear()
graphics& love::graphics::clear (int r, int g, int b, int a)
Clears the screen to the given background color.
Parameters
r Red value.
g Green value.
b Blue value.
a (255) Alpha value.
draw() [1/2]
graphics& love::graphics::draw (Image * image, int x, int y, float r, float sx, float sy, float ox, float oy)
Draws an image with the given angle, zoom, and origin.
Parameters
image The image to draw on the screen.
x (0) The position to draw the object (x-axis).
y (0) The position to draw the object (y-axis).
r (0) Orientation (radians).
sx (1) Scale factor (x-axis).
sy (sx) Scale factor (y-axis).
ox (0) Origin offset (x-axis).
oy (0) Origin offset (y-axis).
draw() [2/2]
graphics& love::graphics::draw (Image * image, Quad quad, int x, int y)
Draws an image on screen, using the given Quad as a source.
Parameters
image The image to draw on the screen.
quad The source quad of the image.
x (0) The position to draw the object (x-axis).
y (0) The position to draw the object (y-axis).
ellipse()
graphics& love::graphics::ellipse (const std::string & drawmode, int x, int y, int radiusx, int radiusy)
Draws an ellipse.
Parameters
drawmode How to draw the ellipse. Can be "fill" or "line".
x The position of the center along x-axis.
y The position of the center along y-axis.
radiusx The radius of the ellipse along the x-axis (half the ellipse's width).
radiusy The radius of the ellipse along the y-axis (half the ellipse's height).
getBackgroundColor()
Color love::graphics::getBackgroundColor ()
Retrieves the active background color.
See also
love.graphics.setBackgroundColor
getColor()
Color love::graphics::getColor ()
Gets the current color.
Returns
The active color.
getDefaultFilter()
std::string love::graphics::getDefaultFilter ()
Returns the default scaling filters used with images and fonts.
See also
love.graphics.setDefaultFilter
getDimensions()
Point love::graphics::getDimensions ()
Gets the width and height of the window.
See also
love.graphics.getWidth
love.graphics.getHeight
Returns
A Point refering the x and y size of the window.
getFont()
Font* love::graphics::getFont ()
Retrieve th currently active font.
See also
setFont
line()
graphics& love::graphics::line (int x1, int y1, int x2, int y2)
Draws a line.
Parameters
x1 The position of first point on the x-axis.
y1 The position of first point on the y-axis.
x2 The position of second point on the x-axis.
y2 The position of second point on the y-axis.
newFont() [1/3]
Font* love::graphics::newFont (const std::string & filename, int glyphWidth, int glyphHeight, const std::string & letters)
Creates a new BMFont with the given spec.
Parameters
filename The path to the font image.
glyphWidth The width of each character.
glyphHeight The height of each character.
letters The letters presented in the font image.
Returns
The created BMFont.
newFont() [2/3]
Font* love::graphics::newFont (const std::string & filename, int size)
Creates a new TrueType font, with the given font size.
Parameters
filename (default) The path to the TrueType .ttf font. When not provided, will return the default font.
size (16) The size of the font to create.
Returns
The created TrueType font.
References newFont().
Referenced by newFont().
newFont() [3/3]
Font* love::graphics::newFont (int size)
Creates a new pixel font at the given size.
Parameters
size (8) The size of the font to create.
Returns
The created Pixel font.
References newFont().
newImage()
Image* love::graphics::newImage (const std::string & filename)
Creates a new Image from a given filepath.
Parameters
filename The filepath to the image file.
Returns
An image object which can be drawn to the screen.
var logo = love.graphics.newImage("logo.png")
point() [1/2]
graphics& love::graphics::point (int x, int y)
Draws a point.
Parameters
x The position on the x-axis.
y The position on the y-axis.
point() [2/2]
graphics& love::graphics::point (Point * p)
Draws a point.
Parameters
p The point to draw on the screen.
print()
graphics& love::graphics::print (const std::string & text, int x, int y)
Prints the given text to the screen.
Parameters
text The text to draw.
x (0) The position to draw the object (x-axis).
y (0) The position to draw the object (y-axis).
love.graphics.print("Hello World", 100, 100)
rectangle()
graphics& love::graphics::rectangle (const std::string & drawmode, int x, int y, int width, int height)
Draws a rectangle.
Parameters
drawmode How to draw the rectangle. Can be "fill" or "line".
x The position of top-left corner along the x-axis.
y The position of top-left corner along the y-axis.
width Width of the rectangle.
height Height of the rectangle.
love.graphics.rectangle("fill", 100, 100, 50, 50)
setBackgroundColor()
graphics& love::graphics::setBackgroundColor (int red, int green, int blue, int alpha)
Sets the background color to the given color.
Parameters
red The r value.
green The g value.
blue The b value.
alpha (255) The a value.
See also
love.graphics.getBackgroundColor
setColor()
graphics& love::graphics::setColor (int red, int green, int blue, int alpha)
Sets the active drawing color to the given color.
Parameters
red The amount of red.
green The amount of green.
blue The amount of blue.
alpha (255) The amount of alpha.
See also
getColor
setDefaultFilter()
graphics& love::graphics::setDefaultFilter (const std::string & filter)
Sets the default scaling filters used with images, and fonts.
Parameters
filter The filter mode to apply when rotating or scaling graphics. This can be either "linear" (default), or "nearest".
See also
love.graphics.getDefaultFilter
https://love2d.org/wiki/FilterMode
setFont()
graphics& love::graphics::setFont (Font * font)
Set an already-loaded Font as the current font.
Parameters
(font) The font to set as the active font. When not provided will set the default font.
See also
getFont
References setFont().
Referenced by setFont().